[GG-2576] Build Map Component
sshalu12/geovisualizer pull request #10
Opened 2022-03-29 09:49 UTC by sshalu12

Build Map component

2022-03-29 12:46 UTC, ashutoshgt requested changes

2022-03-29 12:46 UTC, ashutoshgt commented on app/package.json
> +  "name": "reactt",
why did we change the name?

2022-03-29 12:46 UTC, ashutoshgt commented on app/public/index.html
> -    <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
why did we remove this?

2022-03-29 12:46 UTC, ashutoshgt commented on app/public/index.html
> +    <title>Mapbox Data</title>
```suggestion
    <title>GeoVisualiser</title>
```

2022-03-29 12:46 UTC, ashutoshgt commented on app/src/index.css
> +
remove extra lines and add a single new line at end of file (eof)

2022-03-29 15:56 UTC, gtvikas commented on app/src/state.js
> +    if (map.current) return; // initialize map only once
@ashutoshgt as i understand whenever we are clicking state to poi or poi to state, components are getting rendered completely, which will have `map.current` set to null. What is the need of this condition in current scenario

2022-04-04 08:23 UTC, ashutoshgt approved these changes

2022-04-04 09:46 UTC, merged