setup dockerized flask server
sshalu12/geovisualizer pull request #17
Opened 2022-04-18 18:36 UTC by sshalu12

[GG-2605] Setup dockerized flask server

2022-04-19 08:46 UTC, ashutoshgt requested changes
Please add a Makefile and readme specifically for flask_server giving instructions on how to run the flask server and on which port it will be accessible on the browser. 

You may use the existing Readme and Makefile or create a new one.

2022-04-19 11:34 UTC, sushilsingh95 approved these changes

2022-04-20 06:29 UTC, gtvikas approved these changes

2022-04-21 08:04 UTC, ashutoshgt approved these changes

2022-04-21 08:23 UTC, sushilsingh95 reviewed
Should we use `app` or any other more relevant name instead of `flask_server`?

2022-04-21 08:37 UTC, merged