[GG-2483]fetch state data create geojson
sshalu12/geovisualizer pull request #3
Opened 2022-02-23 09:49 UTC by sshalu12

fetch state data and create geojson file

2022-02-23 11:49 UTC, gtvikas requested changes
@sshalu12  Don't use `single letters` to name the variables. Give them proper descriptive names

2022-02-23 11:49 UTC, gtvikas commented on script/state.py
> +conn.close()
remove EOF

2022-02-23 11:51 UTC, gtvikas requested changes

2022-02-23 11:51 UTC, gtvikas commented on script/state.py
> +print(query)
remove this print statement

2022-02-23 11:51 UTC, gtvikas commented on script/state.py
> +                    "id":query[i][0],
Check the formatting here

2022-02-23 11:51 UTC, gtvikas commented on script/state.py
> +         "features": k})
Check the formatting here as well

2022-02-23 11:53 UTC, gtvikas requested changes

2022-02-23 11:53 UTC, gtvikas commented on script/state.py
> +pwd=''
What is the user of this pwd, when you are passing the blank value while creating connection

2022-02-24 10:06 UTC, sushilsingh95 requested changes

2022-02-24 10:06 UTC, sushilsingh95 commented on script/state.py
> +multiploygon = cur.fetchall()
Can we use a single query to all data in 1 query?

2022-02-24 10:06 UTC, sushilsingh95 commented on script/state.py
> +for i in range(0, len(query)):
can we directly iterate over query?

2022-02-24 10:06 UTC, sushilsingh95 commented on script/state.py
> +except EOFError as e:
Is this the only type of error that we get. E.g. can we get permissions error?

2022-02-24 10:06 UTC, sushilsingh95 commented on script/state.py
> +conn.close()
can we move this line to just after we are done with all db queries?

2022-02-24 10:06 UTC, sushilsingh95 commented on docker-compose.yml
> +    command: [ "./usr/script/wait-for-postgres.sh","postgres","python", "./usr/script/state.py"]
is there any particular reason for creating the file in this directory

2022-02-24 12:33 UTC, ashutoshgt commented
Please use docker-compose run with makefile to parametrize the command for our python service in the docker-compose file.

2022-02-28 07:44 UTC, ashutoshgt requested changes

2022-02-28 07:44 UTC, ashutoshgt commented on script/state.py
> +state = []
```suggestion
states = []
```

2022-02-28 07:44 UTC, ashutoshgt commented on script/state.py
> +query = cur.fetchall()
These are results of the query, hence can be named better like `query_results` or `states_data`

2022-02-28 07:44 UTC, ashutoshgt commented on script/state.py
> +for i in query:
```suggestion
for row in states_data:
```

2022-02-28 08:19 UTC, ashutoshgt approved these changes

2022-02-28 08:20 UTC, merged