GG 2486/upload poi mbtiles to mapbox account
sshalu12/geovisualizer pull request #7
Opened 2022-03-08 08:31 UTC by sshalu12

Upload mbtiles to mapbox account

2022-03-11 08:46 UTC, ashutoshgt requested changes

2022-03-11 08:46 UTC, ashutoshgt commented on Dockerfile-python
> +  && apt -y install git build-essential libsqlite3-dev zlib1g-dev
```suggestion
  && apt -y install git build-essential libsqlite3-dev zlib1g-dev postgresql
```

2022-03-11 08:46 UTC, ashutoshgt commented on Dockerfile-python
> +RUN apt install -y postgresql \
remove this line

2022-03-11 08:46 UTC, ashutoshgt commented on script/poi.py
>  query=cur.fetchall()
```suggestion
poi_data=cur.fetchall()
```

2022-03-11 08:46 UTC, ashutoshgt commented on script/poi.py
> +if(len(query)==0):
```suggestion
if len(query)==0:
```

2022-03-11 08:46 UTC, ashutoshgt commented on script/poi.py
> +    print("No data fetched from database ")
use logging module here

2022-03-11 08:46 UTC, ashutoshgt commented on script/poi.py
> +service= Uploader()
```suggestion
service = Uploader()
```

2022-03-11 08:46 UTC, ashutoshgt commented on script/poi.py
> +    script in sleep mode for 5 second and then retry"""
```suggestion
    """ 
      Response status code 422 indicates that the server understands the content type of the request entity,
      and the syntax of the request entity is correct, but it was unable to process the contained instructions. To 
      overcome this problem put the script in sleep mode for 5 seconds and then retry.
     """
```

2022-03-15 07:21 UTC, sshalu12 commented on Dockerfile-python
> +  && apt -y install git build-essential libsqlite3-dev zlib1g-dev
Done

2022-03-15 07:21 UTC, sshalu12 commented on Dockerfile-python
> +RUN apt install -y postgresql \
Done

2022-03-15 07:21 UTC, sshalu12 commented on script/poi.py
>  query=cur.fetchall()
Done

2022-03-15 07:21 UTC, sshalu12 commented on script/poi.py
> +if(len(query)==0):
Done

2022-03-15 07:21 UTC, sshalu12 commented on script/poi.py
> +service= Uploader()
Done

2022-03-15 07:21 UTC, sshalu12 commented on script/poi.py
> +    script in sleep mode for 5 second and then retry"""
Done

2022-03-15 17:07 UTC, ashutoshgt requested changes

2022-03-15 17:07 UTC, ashutoshgt commented on script/poi.py
> +    """
there's an extra indentation here, please shift this to the left

2022-03-16 06:41 UTC, ashutoshgt approved these changes

2022-03-16 07:46 UTC, merged